import { AxiosResponse } from "axios";
import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import ArticleList from "../components/ArticleList";
import Tabs from "../components/Tabs";
import Pagination from "../components/Pagination";

interface IPropTypes {
  categories: {};
  articles: {};
}

const Home: NextPage<IPropTypes> = ({ categories, articles }) => {
  return (
    <div>
      <Head>
        <title>DevMirza Blog Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tabs />
      <ArticleList />
      <Pagination />
    </div>
  );
};

export default Home;
