name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  node-js-ci:
    name: Node.js CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Change to your desired Node.js version

      - name: Enable Corepack
        run: corepack enable
        
      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: yarn build
